FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD vendingMachine.jar /opt/vendingMachine/
EXPOSE 8080
WORKDIR /opt/vendingMachine/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "vendingMachine.jar"]
